# Generated by Django 4.2.4 on 2023-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=50)),
                ('name', models.TextField(max_length=50)),
                ('serial_number', models.TextField(max_length=10)),
                ('location', models.TextField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stock_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
    ]
