# Generated by Django 4.2.4 on 2023-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_alter_stock_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(null=True, upload_to='stock/'),
        ),
    ]
