# Generated by Django 4.2.4 on 2023-11-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_direction_alter_stock_category_alter_stock_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='name',
            new_name='direction',
        ),
    ]
